name: Build and Test Heap Exploitation PoC

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Clone how2heap repository
        run: git clone --depth 1 https://github.com/shellphish/how2heap.git

      - name: List repository structure
        run: |
          echo "Repository root:"
          ls -l .
          echo "Listing subdirectories:"
          for dir in $(find . -maxdepth 1 -type d); do
            echo "Contents of ${dir}:"
            ls -l "${dir}"
          done

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc gdb

      - name: Compile fastbin_dup PoC (glibc_2.35)
        run: gcc -o fastbin_dup how2heap/glibc_2.35/fastbin_dup.c

      - name: Run PoC
        run: ./fastbin_dup
