name: Heap Exploitation PoC
on: [push]  # Run on every push (you can adjust events as needed)
jobs:
  run-heap-exploit:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner&#8203;:contentReference[oaicite:5]{index=5}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4  # Best practice to fetch code&#8203;:contentReference[oaicite:6]{index=6}
      - name: Install dependencies (gcc and gdb)
        run: sudo apt-get update && sudo apt-get install -y gcc gdb  # Install needed packages&#8203;:contentReference[oaicite:7]{index=7}&#8203;:contentReference[oaicite:8]{index=8}
      - name: Clone how2heap repository (optional if code is already present)
        run: git clone --depth 1 https://github.com/shellphish/how2heap.git
      - name: Compile heap exploitation PoC
        run: gcc -o fastbin_dup how2heap/fastbin_dup.c  # Compile the PoC C file into an executable
      - name: Execute heap exploitation PoC
        run: ./fastbin_dup  # Run the PoC; output will be captured in the logs
